export PILO_USER=u
export PILO_PRIMARY_ROOT=z0-att/pri
export PILO_SECONDARY_ROOTS="z1-rem/bak/pri z2-rem/bak/pri"
export PILO_PATH=/z
export PILO_ADMIN_PATH=/z/admin
export PILO_INTAKE_PATH=/z/intake
export PILO_PILE_PATH=/z/pile
export PILO_STATIC_PATH=/z/static
export PILO_STREAM_OUTPUT_PATH=/tmp
export PILO_STREAM_EXPORT=1
