#!/bin/sh
set -eu

cmd=${1:-}
[ -z "$cmd" ] || shift

case "$cmd" in
    "")
        echo "ERROR: missing command"
        exit 1
        ;;
esac

[ -n "$SYSTEM_ROOT" ] || {
    echo "ERROR: SYSTEM_ROOT not set"
    exit 1
}

if ! zfs list "$SYSTEM_ROOT" >/dev/null 2>&1
then
    echo "ERROR: dataset does not exist: $SYSTEM_ROOT"
    exit 1
fi

exec "system-$cmd" "$@"
