#!/bin/sh
set -e

ROOT=tank/data

#zfs create -p $ROOT/active/pile-intake
#zfs create -p $ROOT/active/pile-readonly
#zfs create -p $ROOT/active/admin
#zfs create -p $ROOT/stash
#zfs create -p $ROOT/static/collection
#zfs create -p $ROOT/static/filing

# writable areas
zfs set readonly=off $ROOT/active/pile-intake
zfs set readonly=off $ROOT/active/admin
zfs set readonly=off $ROOT/stash

# protected areas
zfs set readonly=on $ROOT/active/pile-readonly
zfs set readonly=on $ROOT/static
