#!/bin/sh
set -eu

DATASET=$SYSTEM_ROOT/active/pile-readonly
MOUNT=$SYSTEM_PATH/active/pile-readonly
MANIFEST=$MOUNT/.manifest

zfs list "$DATASET" >/dev/null 2>&1 || {
    echo "ERROR: missing required dataset: $DATASET"
    exit 1
}

TMP=$(mktemp)

cd $MOUNT

find . -type f ! -name .manifest -print0 \
  | LC_COLLATE=C sort -z \
  | xargs -r0 sha256sum > "$TMP"

zfs set readonly=off $DATASET
mv "$TMP" $MANIFEST
zfs set readonly=on $DATASET
