#!/bin/sh
set -e

PILE_DATASET=$SYSTEM_ROOT/active/pile-readonly
PILE_PATH=$SYSTEM_PATH/active/pile-readonly
INTAKE_PATH=$SYSTEM_PATH/active/pile-intake

tmp_list=$(mktemp)
trap "rm -f '$tmp_list'" EXIT

find "$INTAKE_PATH" -type f | LC_COLLATE=C sort > "$tmp_list"

while IFS= read -r src
do
    rel=${src#$INTAKE_PATH/}
    dst="$PILE_PATH/in/$rel"
    dst_dir=$(dirname "$dst")

    if [ -f "$dst" ]
    then
        if cmp -s "$src" "$dst"
        then
            rm "$src" # idempotent
        else
            echo "ERROR: name collision with different content: '$rel'"
            exit 1
        fi
    else
        zfs set readonly=off $PILE_DATASET
        mkdir -p "$dst_dir"
        mv "$src" "$dst"
        zfs set readonly=on $PILE_DATASET
    fi
done < "$tmp_list"

system-manifest-update
