#!/bin/sh

SRC="tank/data/active/pile-readonly"
DST="tank/replica/pile-readonly"

# find latest common snapshot
LAST_SRC=$(zfs list -t snapshot -o name -s creation | grep "^$SRC@" | tail -n1)
LAST_DST=$(zfs list -t snapshot -o name -s creation | grep "^$DST@" | tail -n1)

if [ -z "$LAST_DST" ]; then
    zfs send "$LAST_SRC" | zfs receive "$DST"
else
    SNAP_NAME=$(echo "$LAST_SRC" | cut -d@ -f2)
    BASE_NAME=$(echo "$LAST_DST" | cut -d@ -f2)

    if [ "$SNAP_NAME" = "$BASE_NAME" ]; then
        exit 0
    fi

    zfs send -i "$SRC@$BASE_NAME" "$LAST_SRC" | zfs receive "$DST"
fi
