#!/bin/sh

PILE=/tank/data/active/pile
MANIFEST=$PILE/.manifest

TMP=$(mktemp)

cd $PILE

find . -maxdepth 1 -type f ! -name .manifest -print0 \
  | LC_COLLATE=C sort -z \
  | xargs -0 sha256sum > "$TMP"

mv "$TMP" $MANIFEST
