#!/bin/sh
set -e

SRC=${1:-tank/data}
DST=${2:-tank/replica/data}

latest_guid() {
    zfs list -t snap -s creation -Ho guid "$1" | tail -n1
}

SRC_GUID=$(latest_guid "$SRC")
DST_GUID=$(latest_guid "$DST")

if [ -z "$DST_GUID" ]
then
    echo "ERROR: no snapshots on target"
    exit 1
fi

SRC_GUIDS=$(mktemp)
DST_GUIDS=$(mktemp)

trap "rm $SRC_GUIDS $DST_GUIDS" EXIT

zfs list -d 9999 -t snap -Ho guid "$SRC" | sort > "$SRC_GUIDS"
zfs list -d 9999 -t snap -Ho guid "$DST" | sort > "$DST_GUIDS"

if comm -23 "$DST_GUIDS" "$SRC_GUIDS" | grep -q .
then
    echo "ERROR: replication divergence"
    rm -f "$SRC_GUIDS" "$DST_GUIDS"
    exit 1
fi

if [ "$SRC_GUID" != "$DST_GUID" ]
then
    echo "ERROR: replication behind"
    exit 1
fi
