#!/bin/sh
set -e

INTAKE=/tank/data/active/pile-intake
CANON=/tank/data/active/pile-readonly

for src in $INTAKE/*
do
    [ -f "$src" ] || continue
    if [ -f $CANON/$(basename "$src") ]
    then
        rm "$src"
    else
        mv "$src" $CANON/
    fi
done
