#!/bin/sh
set -e

PILE="tank/data/active/pile-readonly"

CMD="$1"

[ -n "$CMD" ] || {
    echo "ERROR: missing command"
    exit 1
}


exec_op() {
    op="$1"
    src="$2"
    dst="$3"

    case "$op" in
        mv) ;;
        *)
            echo "ERROR: unsupported operation: '$op'"
            exit 1
            ;;
    esac

    case "$src" in
        /*|*..*)
            echo "ERROR: invalid source path"
            exit 1
            ;;
    esac

    case "$dst" in
        /*|*..*)
            echo "ERROR: invalid destination path"
            exit 1
            ;;
    esac

    SRC="/$PILE/$src"
    DST="/$PILE/$dst"

    [ -f "$SRC" ] || {
        echo "ERROR: source missing: $src"
        exit 1
    }

    DIR=$(dirname "$DST")

    if [ -f "$DST" ]
    then
        if cmp -s "$SRC" "$DST"
        then
            rm "$SRC"
        else
            echo "ERROR: destination conflict: $dst"
            exit 1
        fi
    else
        mkdir -p "$DIR"
        mv "$SRC" "$DST"
    fi
}

tmp=$(mktemp)
printf "%s\n" "$CMD" > "$tmp"

zfs set readonly=off $PILE
while read -r op src dst
do
    [ -n "$op" ] || continue
    exec_op "$op" "$src" "$dst" || break
done < $tmp

zfs set readonly=on $PILE
rm -f "$tmp"
system-manifest-update
