#!/bin/sh
set -eu

cmd=${1:-}
[ -z "$cmd" ] || shift

case "$cmd" in
    "")
        echo "ERROR: missing command"
        exit 1
        ;;
esac

[ -n "$SYSTEM_ROOT" ] || {
    echo "ERROR: SYSTEM_ROOT not set"
    exit 1
}

exec "system-$cmd" "$@"
