#!/bin/sh
set -e

DATASET=$SYSTEM_ROOT/active/pile-readonly
MOUNT=$SYSTEM_PATH/active/pile-readonly

with_writable() {
    dataset=$1
    shift
    zfs set readonly=off $dataset
    set +e
    "$@"
    result=$?
    set -e
    zfs set readonly=on $dataset
    [ $result -eq 0 ] || exit $result
}

with_writable $DATASET \
    find "$MOUNT" -mindepth 2 -type d -empty -delete
