#!/bin/sh
set -e

get_incr_basis() {
    local dst_guid=$(zfs list -t snapshot -Ho guid -s creation "$DST" | tail -n1)

    zfs list -t snapshot -o name,guid "$SRC" \
        | awk -v g="$dst_guid" '$2 == g { print $1 }'
}

get_latest_rotation_anchor() {
    zfs list -t snap -s creation -Ho name "$SRC" \
        | grep "@rotation-" \
        | tail -n1
}

is_anchor_on_target() {
    anchor="$1"
    guid=$(zfs list -t snap -Ho guid "$anchor" 2>/dev/null || true)

    [ -n "$guid" ] || return 1

    zfs list -d 9999 -t snap -Ho guid "$DST" \
        | grep -q "^$guid$"
}

get_latest_common_anchor() {
    zfs list -t snap -s creation -Ho name "$SRC" \
        | grep "@rotation-" \
        | while read -r snap
        do
            if is_anchor_on_target "$snap"
            then
                echo "$snap"
            fi
        done \
        | tail -n1
}

SRC="${1:-tank/data}"
DST="${2:-tank/replica/data}"

LAST_SRC=$(zfs list -t snapshot -Ho name -s creation "$SRC" | tail -n1)
LAST_DST=$(zfs list -t snapshot -Ho name -s creation "$DST" | tail -n1) 2>/dev/null

if [ -z "$LAST_SRC" ]
then
    echo "ERROR: no source snapshot"
    exit 1
fi

if [ -z "$LAST_DST" ]
then
    zfs send -R "$LAST_SRC" \
        | zfs receive -h -F "$DST"
else

    ANCHOR=$(get_latest_common_anchor)

    if [ -n "$ANCHOR" ]
    then
        BASE="$ANCHOR"
    else
        BASE=$(get_incr_basis)
    fi

    if [ "$LAST_SRC" = "$BASE" ]
    then
        exit 0
    fi

    [ -n "$BASE" ] || {
        echo "ERROR: base snapshot missing on source: $BASE"
        exit 1
    }
    zfs send -h -R -I "$BASE" "$LAST_SRC" \
        | zfs receive -u -o readonly=on -F "$DST"
fi
