# vim: filetype=sshconfig
host pi10
    hostname 192.168.1.10
    user u
    identityfile ~/.ssh/config.d/pi10_user_key
    userknownhostsfile ~/.ssh/config.d/pi10_known_hosts
    compression no
    controlmaster auto
