#!/bin/sh
set -eu

HERE=$(dirname $(readlink -f "$0"))
. "$HERE"/lib.sh

require_arg "${1:-}" "replica dataset"
require_arg "${2:-}" "original dataset"
require_arg "${3:-}" "snapshot dataset"

SRC="$1"
DST="$2"
SNAP="$3"

zfs destroy -r "$DST" 2>/dev/null || true
zfs send -R "$SRC@$SNAP" | zfs receive "$DST"
